version: "3"

services:
    sqlite3:
        image: nouchka/sqlite3:latest
        stdin_open: true
        tty: true
        volumes:
            - ./db/:/root/db/
    # PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: digitalocean.com/php
        container_name: app
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        ports:
            - "9000:9000"
            - "3000:3000"
        networks:
            - app-network

    # Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "80:80"
            - "8080:8080"
        networks:
            - app-network

# Docker Networks
networks:
    app-network:
        driver: bridge
